source 'https://rubygems.org'

gem 'addressable', '~> 2.4.0'
gem 'typhoeus', '~> 1.1.0'
gem 'nokogiri', '~> 1.6.8.1'
gem 'dearchiver', '~> 0.0'
gem 'json', '~> 2.0.2'
gem 'activesupport', '~> 5.0.0.1'
gem 'dm-core', '~> 1.2.0'
gem 'dm-migrations', '~> 1.2.0'
gem 'dm-constraints', '~> 1.2.0'
gem 'dm-sqlite-adapter', '~> 1.2.0'
gem 'cms_scanner', '~> 0.0.37'
