source 'https://rubygems.org'

gem 'activesupport', '~> 5.0'
gem 'addressable', '~> 2.5'
gem 'bundler', '~> 1.6'
gem 'cms_scanner', '~> 0.0.37.9'
gem 'dearchiver', '~> 0.0'
gem 'dm-constraints', '~> 1.2.0'
gem 'dm-core', '~> 1.2.0'
gem 'dm-migrations', '~> 1.2.0'
gem 'dm-sqlite-adapter', '~> 1.2.0'
gem 'json', '~> 2.1'
gem 'nokogiri', '~> 1.7'
gem 'typhoeus', '~> 1.1'
