source 'https://rubygems.org'

gem 'addressable', '~> 2.3.8'
gem 'typhoeus', '~> 0.7'
gem 'nokogiri', '~> 1.6'
gem 'dearchiver', '~> 0.0'
gem 'json', '~> 1.8'
gem 'activesupport', '~> 4.2'
gem 'dm-core', '~> 1.2'
gem 'dm-migrations', '~> 1.2'
gem 'dm-constraints', '~> 1.2'
gem 'dm-sqlite-adapter', '~> 1.2'
