require 'fingerprinter'
require 'fingerprinters/wordpress'
require 'fingerprinters/fckeditor'
require 'fingerprinters/apache_icons'
require 'fingerprinters/phpmyadmin'
require 'fingerprinters/tiny_mce'
